/**
 * A plausible French B2B draft, and a helper to vary it.
 *
 * One shared starting point keeps each test's `override` to the single field it is actually about,
 * so what a test is testing is visible in the call rather than buried in a wall of boilerplate.
 */

import type { DraftLine, InvoiceDraft } from '../../src/generate/draft.js';

/** A plumber billing a bakery in Lyon. Both SIRETs pass the Luhn check. */
export const BASE_DRAFT: InvoiceDraft = {
  invoiceNumber: 'FA-2026-0087',
  typeCode: '380',
  issueDate: '2026-09-03',
  dueDate: '2026-10-03',
  currency: 'EUR',
  buyerReference: 'SERVICE-ACHATS',
  seller: {
    name: 'Plomberie Diderot SARL',
    siret: '55208131700018',
    vatId: 'FR03552081317',
    address: {
      line1: '14 rue Diderot',
      postcode: '69001',
      city: 'Lyon',
      countryCode: 'FR',
    },
  },
  buyer: {
    name: 'Boulangerie Martin SAS',
    siret: '44306184100005',
    vatId: 'FR64443061841',
    address: {
      line1: '12 rue de la République',
      postcode: '69002',
      city: 'Lyon',
      countryCode: 'FR',
    },
  },
  lines: [
    {
      name: 'Remplacement chauffe-eau 200 L',
      quantity: '1',
      unitCode: 'C62',
      unitPrice: '1250.00',
      vatCategory: 'S',
      vatRatePercent: '20.00',
    },
    {
      name: "Main-d'œuvre installation",
      quantity: '6',
      unitCode: 'HUR',
      unitPrice: '65.00',
      vatCategory: 'S',
      vatRatePercent: '20.00',
    },
    {
      name: 'Déplacement et mise en service',
      quantity: '1',
      unitCode: 'C62',
      unitPrice: '90.00',
      vatCategory: 'S',
      vatRatePercent: '20.00',
    },
  ],
  paymentMeansCode: '30',
  iban: 'FR7630006000011234567890189',
};

export function draftWith(override: Partial<InvoiceDraft>): InvoiceDraft {
  return { ...BASE_DRAFT, ...override };
}

export function lineWith(override: Partial<DraftLine>): DraftLine {
  return { ...BASE_DRAFT.lines[0]!, ...override };
}

/** A fixed clock, so generated bytes are comparable across runs. */
export const FIXED_NOW = new Date('2026-09-03T09:00:00.000Z');
